function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Task1"};
	this.sidHashMap["Task1"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "Task1:28"};
	this.sidHashMap["Task1:28"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Input1"] = {sid: "Task1:29"};
	this.sidHashMap["Task1:29"] = {rtwname: "<Root>/Input1"};
	this.rtwnameHashMap["<Root>/Input2"] = {sid: "Task1:34"};
	this.sidHashMap["Task1:34"] = {rtwname: "<Root>/Input2"};
	this.rtwnameHashMap["<Root>/Add"] = {sid: "Task1:1"};
	this.sidHashMap["Task1:1"] = {rtwname: "<Root>/Add"};
	this.rtwnameHashMap["<Root>/Add1"] = {sid: "Task1:20"};
	this.sidHashMap["Task1:20"] = {rtwname: "<Root>/Add1"};
	this.rtwnameHashMap["<Root>/Constant3"] = {sid: "Task1:25"};
	this.sidHashMap["Task1:25"] = {rtwname: "<Root>/Constant3"};
	this.rtwnameHashMap["<Root>/Divide"] = {sid: "Task1:5"};
	this.sidHashMap["Task1:5"] = {rtwname: "<Root>/Divide"};
	this.rtwnameHashMap["<Root>/Product"] = {sid: "Task1:6"};
	this.sidHashMap["Task1:6"] = {rtwname: "<Root>/Product"};
	this.rtwnameHashMap["<Root>/Sqrt"] = {sid: "Task1:8"};
	this.sidHashMap["Task1:8"] = {rtwname: "<Root>/Sqrt"};
	this.rtwnameHashMap["<Root>/Subtract"] = {sid: "Task1:2"};
	this.sidHashMap["Task1:2"] = {rtwname: "<Root>/Subtract"};
	this.rtwnameHashMap["<Root>/Subtract1"] = {sid: "Task1:21"};
	this.sidHashMap["Task1:21"] = {rtwname: "<Root>/Subtract1"};
	this.rtwnameHashMap["<Root>/Unary Minus"] = {sid: "Task1:7"};
	this.sidHashMap["Task1:7"] = {rtwname: "<Root>/Unary Minus"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "Task1:30"};
	this.sidHashMap["Task1:30"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "Task1:31"};
	this.sidHashMap["Task1:31"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "Task1:32"};
	this.sidHashMap["Task1:32"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "Task1:33"};
	this.sidHashMap["Task1:33"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<Root>/Output4"] = {sid: "Task1:35"};
	this.sidHashMap["Task1:35"] = {rtwname: "<Root>/Output4"};
	this.rtwnameHashMap["<Root>/Output5"] = {sid: "Task1:36"};
	this.sidHashMap["Task1:36"] = {rtwname: "<Root>/Output5"};
	this.rtwnameHashMap["<Root>/Output6"] = {sid: "Task1:37"};
	this.sidHashMap["Task1:37"] = {rtwname: "<Root>/Output6"};
	this.rtwnameHashMap["<Root>/Output7"] = {sid: "Task1:38"};
	this.sidHashMap["Task1:38"] = {rtwname: "<Root>/Output7"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
